---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - metricbeat

- name: uninstall metricbeat elastic packages
  package:
    name: "{{ metricbeat_package_names_els }}"
    state: absent
  when:
    - (not metricbeat_packages is defined) or (metricbeat_package_names_els not in metricbeat_packages)
    - metricbeat_oss | bool

- name: install metricbeat oss packages
  package:
    name: "{{ metricbeat_packages | default(metricbeat_package_names_oss) }}"
    state: "{{ metricbeat_package_state }}"
  when: metricbeat_oss | bool
  notify: install metricbeat template

- name: uninstall metricbeat oss packages
  package:
    name: "{{ metricbeat_package_names_oss }}"
    state: absent
  when:
    - (not metricbeat_packages is defined) or (metricbeat_package_names_oss not in metricbeat_packages)
    - not (metricbeat_oss | bool)

- name: install yum version lock support
  package:
    name: yum-plugin-versionlock
  when: ansible_os_family == 'RedHat'

- name: disable yum package lock
  command: "yum versionlock delete {{ item }}"
  ignore_errors: yes
  loop: "{{ [metricbeat_packages | default(metricbeat_package_names_els)] | flatten }}"
  when: ansible_os_family == 'RedHat'

- name: disable apt package lock
  command: "apt-mark unhold {{ item }}"
  loop: "{{ [metricbeat_packages | default(metricbeat_package_names_els)] | flatten }}"
  when: ansible_os_family == 'Debian'

- name: install metricbeat elastic packages
  package:
    name: "{{ metricbeat_packages | default(metricbeat_package_names_els) }}"
    state: "{{ metricbeat_package_state }}"
  when: not (metricbeat_oss | bool)
  notify: install metricbeat template

- name: enable apt package hold
  command: "apt-mark hold {{ item }}"
  loop: "{{ [metricbeat_packages | default(metricbeat_package_names_els)] | flatten }}"
  when:
    - ansible_os_family == 'Debian'
    - metricbeat_version_lock | bool

- name: enable yum package lock
  command: "yum versionlock add {{ item }}"
  ignore_errors: yes
  loop: "{{ [metricbeat_packages | default(metricbeat_package_names_els)] | flatten }}"
  when:
    - ansible_os_family == 'RedHat'
    - metricbeat_version_lock | bool

- name: inspect packages
  package_facts:
    manager: auto

- name: configure metricbeat
  copy:
    content: |
      # Ansible managed

      {{ metricbeat_conf | to_nice_yaml(indent=2) }}
    dest: "{{ metricbeat_conf_path }}"
  notify: restart metricbeat
  when:
    - metricbeat_conf_manage | bool

- name: manage metricbeat services
  service:
    name: "{{ metricbeat_service_name }}"
    state: "{{ metricbeat_service_status }}"
    enabled: "{{ metricbeat_service_enabled }}"
