---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/main.yml"
  tags:
    - metricbeat

- name: install metricbeat packages
  package:
    name: "{{ metricbeat_packages }}"
    state: "{{ metricbeat_package_state }}"
  notify: install metricbeat template

- name: inspect packages
  package_facts:
    manager: auto

- name: configure metricbeat
  copy:
    content: |
      # Ansible managed

      {{ metricbeat_conf | to_nice_yaml(indent=2) }}
    dest: "{{ metricbeat_conf_path }}"
  notify: restart metricbeat
  when:
    - metricbeat_conf_manage | bool

- name: manage metricbeat services
  service:
    name: "{{ metricbeat_service_name }}"
    state: "{{ metricbeat_service_status }}"
    enabled: "{{ metricbeat_service_enabled }}"
